name: auto-approve
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.event.pull_request.user.login == 'AsPulse' && !github.event.pull_request.draft
    steps:
      - uses: hmarr/auto-approve-action@v3
